'use client';

import { useMemo, useState } from 'react';

const SAMPLE = `{
  // config generated by hand, oops
  name: 'formatiq',
  "version": "1.0.0",
  "tags": ["json", 'tools', "repair",],
  "active": true
  "count": 3,
}`;

interface Token {
  text: string;
  isString: boolean;
  quote?: '"' | "'";
}

function tokenizeStrings(input: string): Token[] {
  const tokens: Token[] = [];
  let buf = '';
  let i = 0;
  while (i < input.length) {
    const ch = input[i];
    if (ch === '"' || ch === "'") {
      if (buf) {
        tokens.push({ text: buf, isString: false });
        buf = '';
      }
      const quote = ch as '"' | "'";
      let str = ch;
      i++;
      while (i < input.length) {
        const c = input[i];
        if (c === '\\' && i + 1 < input.length) {
          str += c + input[i + 1];
          i += 2;
          continue;
        }
        str += c;
        i++;
        if (c === quote) break;
      }
      tokens.push({ text: str, isString: true, quote });
      continue;
    }
    buf += ch;
    i++;
  }
  if (buf) tokens.push({ text: buf, isString: false });
  return tokens;
}

function stripCommentsFromChunk(text: string): { text: string; changed: boolean } {
  let changed = false;
  let out = text.replace(/\/\*[\s\S]*?\*\//g, () => {
    changed = true;
    return ' ';
  });
  out = out.replace(/\/\/[^\n]*/g, () => {
    changed = true;
    return '';
  });
  return { text: out, changed };
}

function normalizeQuoteToken(token: Token): { text: string; changed: boolean } {
  if (!token.isString || token.quote === '"') {
    return { text: token.text, changed: false };
  }
  // Single-quoted string: unwrap, un-escape \' back to ', escape bare " to \", rewrap in double quotes.
  const inner = token.text.slice(1, -1);
  const content = inner.replace(/\\'/g, "'").replace(/(?<!\\)"/g, '\\"');
  return { text: `"${content}"`, changed: true };
}

function quoteUnquotedKeys(text: string): { text: string; changed: boolean } {
  let changed = false;
  const out = text.replace(/([{,]\s*)([A-Za-z_$][A-Za-z0-9_$]*)(\s*:)/g, (match, before, key, after) => {
    changed = true;
    return `${before}"${key}"${after}`;
  });
  return { text: out, changed };
}

function removeTrailingCommas(text: string): { text: string; changed: boolean } {
  let changed = false;
  const out = text.replace(/,(\s*[}\]])/g, (match, after) => {
    changed = true;
    return after;
  });
  return { text: out, changed };
}

function insertMissingCommas(text: string): { text: string; changed: boolean } {
  let changed = false;
  const out = text.replace(/(true|false|null|[0-9"}\]])(\s+)"/g, (match, endToken, ws) => {
    changed = true;
    return `${endToken},${ws}"`;
  });
  return { text: out, changed };
}

interface RepairResult {
  ok: boolean;
  output?: string;
  notes: string[];
  message?: string;
}

function repairJson(input: string): RepairResult {
  if (!input.trim()) {
    return { ok: false, notes: [], message: 'Paste some JSON to repair.' };
  }

  // Already valid — nothing to fix, just pretty-print it.
  try {
    const parsed = JSON.parse(input);
    return { ok: true, output: JSON.stringify(parsed, null, 2), notes: ['No repairs were necessary - this JSON was already valid.'] };
  } catch {
    // fall through to the repair pipeline
  }

  const notes: string[] = [];

  const tokens = tokenizeStrings(input);
  let commentsChanged = false;
  let quotesChanged = false;
  const normalizedTokens = tokens.map((token) => {
    if (token.isString) {
      const { text, changed } = normalizeQuoteToken(token);
      if (changed) quotesChanged = true;
      return text;
    }
    const { text, changed } = stripCommentsFromChunk(token.text);
    if (changed) commentsChanged = true;
    return text;
  });
  if (commentsChanged) notes.push('Removed JavaScript-style comments (// and /* */).');
  if (quotesChanged) notes.push('Converted single-quoted strings to double-quoted strings.');

  let text = normalizedTokens.join('');

  const keysResult = quoteUnquotedKeys(text);
  text = keysResult.text;
  if (keysResult.changed) notes.push('Added double quotes around unquoted object keys.');

  const trailingResult = removeTrailingCommas(text);
  text = trailingResult.text;
  if (trailingResult.changed) notes.push('Removed trailing commas before } or ].');

  const missingCommaResult = insertMissingCommas(text);
  text = missingCommaResult.text;
  if (missingCommaResult.changed) notes.push('Inserted missing commas between properties or array items.');

  try {
    const parsed = JSON.parse(text);
    return { ok: true, output: JSON.stringify(parsed, null, 2), notes };
  } catch (err) {
    return {
      ok: false,
      notes,
      message:
        (err instanceof Error ? err.message : 'Invalid JSON') +
        ' - this input has an issue too significant to auto-repair (e.g. a genuinely mismatched bracket or truncated value). Fix the highlighted area manually and try again.',
    };
  }
}

export default function JsonRepair() {
  const [input, setInput] = useState(SAMPLE);
  const [copied, setCopied] = useState(false);

  const result = useMemo(() => repairJson(input), [input]);

  function copyOutput() {
    if (result.ok && result.output) {
      navigator.clipboard.writeText(result.output);
      setCopied(true);
      setTimeout(() => setCopied(false), 1200);
    }
  }

  return (
    <div>
      <div className="control-row">
        <button className="icon-btn" onClick={() => setInput(SAMPLE)}>
          Load sample
        </button>
        <button className="icon-btn" onClick={() => setInput('')}>
          Clear
        </button>
      </div>

      <div className="panels">
        <div className="panel">
          <div className="panel-bar">
            <span>Broken JSON</span>
          </div>
          <textarea
            className="mono"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            spellCheck={false}
            placeholder="Paste JSON with trailing commas, single quotes, unquoted keys, comments, or missing commas..."
          />
          <div className={`status-line ${result.ok ? 'status-valid' : 'status-invalid'}`}>
            {result.ok ? '✓ Repaired' : `✗ ${result.message}`}
          </div>
        </div>

        <div className="panel">
          <div className="panel-bar">
            <span>Repaired output</span>
            <div className="panel-actions">
              <button className="icon-btn" onClick={copyOutput} disabled={!result.ok}>
                {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
          </div>
          <div className="output mono">
            {result.ok ? result.output : '// This input could not be automatically repaired - see the message above'}
          </div>
        </div>
      </div>

      {result.notes.length > 0 && (
        <div className="panel" style={{ marginTop: 16 }}>
          <div className="panel-bar">
            <span>What was fixed</span>
          </div>
          <div className="output mono">{result.notes.map((note) => `• ${note}`).join('\n')}</div>
        </div>
      )}
    </div>
  );
}
